version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - drextrime

  # Backend dependencies
  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - drextrime

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - drextrime