server.port=${PORT:3000}
spring.application.name=server

# If DATABASE_URL is not provided in .env, default to H2 in-memory
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:matchmedb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# If DDL_AUTO is not set in .env, default to create-drop
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.show-sql=${SHOW_SQL_QUERIES:false}

# Security
jwt.secret=${JWT_SECRET:super-secret-jwt-key-for-matchme-application-testing}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Utilities
spring.jackson.serialization.write-bigdecimal-as-plain=true
logging.level.org.springframework.boot.autoconfigure.security=ERROR
